### ISSUE TITLE
Mock command

### ISSUE THREAD

**Issue by Fraylak** [othello777/boby#7]
add a mock feature where boby makes fun of something/someone: for instance boby mock kiefer

**Comment by Fraylak** [comment]
haha you suck
nice job 100% this is an absolute winner
L + Ratio + Disrespect

**Comment by othello777** [comment]
we need 10 or more total roasts to implement this

**Comment by Fraylak** [comment]
ur mom
loser
is an absolute degenerate
nerd
ahahahaahhaha

**Comment by Fraylak** [comment]
haha you suck
L + Ratio + Disrespect
ur mom
loser
absolute degenerate
nerd
ahahahaahhaha
lol bad
a winner at losing
the dirt beneath my feet

**Comment by othello777** [comment]
added in 4ffd11102f74ea5897a80e66c59495a727e51f94 with the help of @Fraylak
